# Generated by Django 3.2.12 on 2022-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220520_2209'),
        ('accounts', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recently_recommended_movies',
            field=models.ManyToManyField(related_name='recently_recommend', to='movies.Movie'),
        ),
    ]
