# Generated by Django 3.2.12 on 2022-05-25 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_recently_recommended_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_img', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('viewed_date', models.DateField()),
                ('with_person', models.CharField(max_length=30, null=True)),
                ('like', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
