# Generated by Django 3.2.12 on 2022-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shared_poster',
            field=models.TextField(default=''),
        ),
    ]
